"""zh district/street name -> official EN (matching the EN booklet appendix answers)."""
ZH_DISTRICT_EN = {
    '將軍澳': 'Tseung Kwan O',
    '大坑': 'Tai Hang',
    '九龍塘': 'Kowloon Tong',
    '油麻地': 'Yau Ma Tei',
    '荃景圍': 'Tsuen King Circuit',
    '黃竹坑': 'Wong Chuk Hang',
    '黃大仙': 'Wong Tai Sin',
    '天壇街': 'Tin Tan Street',
    '東院道': 'Eastern Hospital Road',
    '灣仔': 'Wan Chai',
    '柴灣': 'Chai Wan',
    '亞公角街': 'A Kung Kok Street',
    '全安路': 'Chuen On Road',
    '九龍城': 'Kowloon City',
    '薄扶林': 'Pok Fu Lam',
    '松仁路': 'Chung Yan Road',
    '西營盤': 'Sai Ying Pun',
    '富健街': 'Fu Kin Street',
    '沙田': 'Sha Tin',
    '屯門': 'Tuen Mun',
    '山頂': 'The Peak',
    '深水埗': 'Sham Shui Po',
    '跑馬地': 'Happy Valley',
    '大埔': 'Tai Po',
    '元朗': 'Yuen Long',
    '荔景': 'Lai King',
    '上水': 'Sheung Shui',
    '寶寧里': 'Po Ning Lane',
    '沙田坳道': 'Shatin Pass Road',
    '黃竹坑徑': 'Wong Chuk Hang Path',
    '青松觀路': 'Tsing Chung Koon Road',
    '九龍灣': 'Kowloon Bay',
    '長沙灣': 'Cheung Sha Wan',
    '荃灣': 'Tsuen Wan',
    '澤祥街': 'Chak Cheung Street',
    '秀茂坪': 'Sau Mau Ping',
    '樂富': 'Lok Fu',
    '承啟道': 'Shing Kai Road',
    '粉嶺': 'Fanling',
    '荷李活道': 'Hollywood Road',
    '中環': 'Central',
    '銅鑼灣': 'Causeway Bay',
    '尖沙咀': 'Tsim Sha Tsui',
    '旺角': 'Mong Kok',
    '佐敦': 'Jordan',
    '太子': 'Prince Edward',
    '深旺道': 'Sham Mong Road',
    '觀塘': 'Kwun Tong',
    '藍田': 'Lam Tin',
    '油塘': 'Yau Tong',
    '調景嶺': 'Tiu Keng Leng',
    '鑽石山': 'Diamond Hill',
    '新蒲崗': 'San Po Kong',
    '彩虹': 'Choi Hung',
    '牛頭角': 'Ngau Tau Kok',
    '土瓜灣': 'To Kwa Wan',
    '紅磡': 'Hung Hom',
    '何文田': 'Ho Man Tin',
    '石硤尾': 'Shek Kip Mei',
    '美孚': 'Mei Foo',
    '荔枝角': 'Lai Chi Kok',
    '南昌': 'Nam Cheong',
    '長沙灣道': 'Cheung Sha Wan Road',
    '青山道': 'Castle Peak Road',
    '葵涌': 'Kwai Chung',
    '青衣': 'Tsing Yi',
    '馬鞍山': 'Ma On Shan',
    '大圍': 'Tai Wai',
    '火炭': 'Fo Tan',
    '科學園': 'Science Park',
    '上環': 'Sheung Wan',
    '中區': 'Central',
    '金鐘': 'Admiralty',
    '北角': 'North Point',
    '鰂魚涌': 'Quarry Bay',
    '太古': 'Taikoo',
    '西灣河': 'Sai Wan Ho',
    '筲箕灣': 'Shau Kei Wan',
    '小西灣': 'Siu Sai Wan',
    '香港仔': 'Aberdeen',
    '鴨脷洲': 'Ap Lei Chau',
    '赤柱': 'Stanley',
    '淺水灣': 'Repulse Bay',
    '數碼港': 'Cyberport',
    '田灣': 'Tin Wan',
    '黃竹坑道': 'Wong Chuk Hang Road',
    '半山': 'Mid-Levels',
    '山頂道': 'Peak Road',
    '大坑道': 'Tai Hang Road',
    '跑馬地馬場': 'Happy Valley Racecourse',
    '啟德': 'Kai Tak',
    '九龍站': 'Kowloon Station',
    '西九龍': 'West Kowloon',
    '奧運': 'Olympic',
    '荔枝角道': 'Lai Chi Kok Road',
    '彌敦道': 'Nathan Road',
    '廣東道': 'Canton Road',
    '廟街': 'Temple Street',
    '上海街': 'Shanghai Street',
    '深水埗區': 'Sham Shui Po',
    '黃竹坑粒': 'Wong Chuk Hang',
    '沙田區': 'Sha Tin',
    '將軍澳工業邨': 'Tseung Kwan O Industrial Estate',
    '機場': 'Airport',
    '赤鱲角': 'Chek Lap Kok',
    '東涌': 'Tung Chung',
    '大嶼山': 'Lantau',
    '昂坪': 'Ngong Ping',
    '梅窩': 'Mui Wo',
    '長洲': 'Cheung Chau',
    '坪洲': 'Peng Chau',
    '南丫島': 'Lamma Island',
    '長沙灣': 'Cheung Sha Wan',
    '西貢': 'Sai Kung',
    '將軍澳': 'Tseung Kwan O',
    '天水圍': 'Tin Shui Wai',
    '朗屏': 'Long Ping',
    '元朗市': 'Yuen Long',
    '屯門市': 'Tuen Mun',
    '沙田市': 'Sha Tin',
    '上環': 'Sheung Wan',
    '西營盤': 'Sai Ying Pun',
    '堅尼地城': 'Kennedy Town',
    '石塘咀': 'Sai Wan',
    '灣仔北': 'Wan Chai North',
    '灣仔區': 'Wan Chai',
    '東區': 'Eastern',
    '南區': 'Southern',
    '九龍城區': 'Kowloon City',
    '深水埗': 'Sham Shui Po',
    '黃大仙區': 'Wong Tai Sin',
    '觀塘區': 'Kwun Tong',
    '西貢區': 'Sai Kung',
    '沙田區': 'Sha Tin',
    '大埔區': 'Tai Po',
    '北區': 'North District',
    '元朗區': 'Yuen Long',
    '屯門區': 'Tuen Mun',
    '荃灣區': 'Tsuen Wan',
    '葵青區': 'Kwai Tsing',
    '離島區': 'Islands',
    '香港迪士尼樂園': 'Hong Kong Disneyland',
    '海洋公園': 'Ocean Park',
    '山頂纜車': 'Peak Tram',
    '會展': 'HKCEC',
    '會議展覽中心': 'Hong Kong Convention and Exhibition Centre',
    '紅磡體育館': 'Hung Hom Coliseum',
    '大球場': 'Hong Kong Stadium',
    '亞洲國際博覽館': 'AsiaWorld-Expo',
    '尖沙咀東': 'Tsim Sha Tsui East',
    '理工大學': 'The Hong Kong Polytechnic University',
    '香港大學': 'The University of Hong Kong',
    '中文大學': 'The Chinese University of Hong Kong',
    '科技大學': 'The Hong Kong University of Science and Technology',
    '浸會大學': 'Hong Kong Baptist University',
    '城市大學': 'City University of Hong Kong',
    '樹仁大學': 'Hong Kong Shue Yan University',
    '恒生大學': 'The Hang Seng University of Hong Kong',
    '嶺南大學': 'Lingnan University',
    '教育大學': 'The Education University of Hong Kong',
    '都會大學': 'Hong Kong Metropolitan University',
    '上禾輋路': 'Sheung Wo Hang Road',
    '中港道': 'Chung Kong Road',
    '亞皆老街': 'Argyle Street',
    '元州街': 'Un Chau Street',
    '加士居道': 'Gascoigne Road',
    '博物館道': 'Museum Drive',
    '啟成街': 'Kai Shing Street',
    '培正道': 'Pui Ching Road',
    '大角咀': 'Tai Kok Tsui',
    '太子道西': 'Prince Edward Road West',
    '安華街': 'On Wah Street',
    '宜正里': 'Yee Ching Lane',
    '寶琳北路': 'Po Lam Road North',
    '小瀝源': 'Siu Lek Yuen',
    '屯喜路': 'Tuen Hi Road',
    '忠孝街': 'Chung Hau Street',
    '掃管笏': 'So Kwun Wat',
    '柯士甸道西': 'Austin Road West',
    '楊屋道': 'Yeung Uk Road',
    '橋樂坊': 'Kiu Lok Square',
    '汀九': 'Ting Kau',
    '汀角路': 'Ting Kok Road',
    '添美道': 'Tim Mei Avenue',
    '清水灣': 'Clear Water Bay',
    '渣華道': 'Java Road',
    '港灣道': 'Harbour Road',
    '源禾路': 'Yuen Wo Road',
    '璧峰路': 'Peak Road',
    '白石角': 'Pak Shek Kok',
    '皇后大道東': "Queen's Road East",
    '竹篙灣': 'Penny\'s Bay',
    '翠嶺里': 'Chui Ling Lane',
    '聯運街': 'Luen Wan Street',
    '興芳路': 'Hing Fong Road',
    '般咸道': 'Bonham Road',
    '英皇道': 'King\'s Road',
    '荔灣道': 'Lai Wan Road',
    '莊士敦道': 'Johnston Road',
    '西樓角路': 'Sai Lau Kok Road',
    '親民街': 'Chun Man Street',
    '車公廟路': 'Che Kung Miu Road',
    '軒尼詩道': 'Hennessy Road',
    '通州街': 'Tung Chau Street',
    '達之路': 'Tat Chee Avenue',
    '達東路': 'Tat Tung Road',
    '金鐘道': 'Queensway',
    '銀鑛灣路': 'Silver Mine Bay Road',
    '馬灣': 'Ma Wan',
    '馬頭圍道': 'Ma Tau Wai Road',
    '馬頭角道': 'Ma Tau Kok Road',
    '鯉魚門道': 'Lei Yue Mun Road',
}
