"""Domain glossary applied BEFORE machine translation (protect proper nouns and
fixed road/transport vocabulary) and canonical translations for recurring exam phrases.
Place names / road names / tunnels are translated with an exact dictionary, then the
residual sentence is passed through opus-mt-zh-en; glossary tokens are restored after."""
import re

# Fixed exam phrase patterns (zh regex -> en template using captured groups)
PHRASE_PATTERNS = [
    (r'^若由(.+?)駛至(.+?)，在正常交通情況下，以及不需考慮隧道收費（如適用）的情形下，哪一條路線最直接可行？$',
     lambda m, g: f'If you drive from {g(m.group(1))} to {g(m.group(2))}, under normal traffic conditions and disregarding tunnel fees (if applicable), which of the following is the most direct viable route?'),
    (r'^(.+?)位於哪裡？$', lambda m, g: f'Where is {g(m.group(1))}?'),
    (r'^圖中交通標誌表示甚麼？$', lambda m, g: 'What does the traffic sign in the picture mean?'),
    (r'^圖中(\d+)號交通標誌表示甚麼？$', lambda m, g: f'What does traffic sign {m.group(1)} in the picture mean?'),
    (r'^在薄霧天氣下，看到此標誌時，你應︰$', lambda m, g: 'In misty weather, when you see this sign, you should:'),
    (r'^駛過水浸的街道後，你應(.*?)。$', lambda m, g: f'After driving through a flooded street, you should {g(m.group(1))}.'),
    (r'^若用以豎立「不准停車」標誌的標誌杆為(.*?)色則代表(.*?)不准停車。$',
     lambda m, g: f'If the pole erecting the "No stopping" sign is {g(m.group(1))}, it means no stopping during {g(m.group(2))}.'),
]

# Term-level glossary: longest-match first. Keys are zh terms, values are EN.
TERMS = {
    # tunnels / strategic routes
    '紅磡海底隧道': 'Cross Harbour Tunnel',
    '海底隧道': 'Cross Harbour Tunnel',
    '東區海底隧道': 'Eastern Harbour Crossing',
    '西區海底隧道': 'Western Harbour Crossing',
    '大老山隧道': "Tate's Cairn Tunnel",
    '獅子山隧道': 'Lion Rock Tunnel',
    '機場隧道': 'Airport Tunnel',
    '啟德隧道': 'Kai Tak Tunnel',
    '城門隧道': 'Shing Mun Tunnels',
    '香港仔隧道': 'Aberdeen Tunnel',
    '大欖隧道': 'Tai Lam Tunnel',
    '尖山隧道': 'Eagle\'s Nest Tunnel',
    '沙田嶺隧道': 'Sha Tin Heights Tunnel',
    '昂船洲大橋': 'Stonecutters Bridge',
    '青馬大橋': 'Tsing Ma Bridge',
    '汀九橋': 'Ting Kau Bridge',
    '青葵公路': 'Kwai Tsing Highway',
    '青沙公路': 'Tsing Sha Highway',
    '西九龍公路': 'West Kowloon Highway',
    '觀塘道': 'Kwun Tong Road',
    '龍翔道': 'Lung Cheung Road',
    '竹園道': 'Chuk Yuen Road',
    '公主道': 'Princess Margaret Road',
    '告士打道': 'Gloucester Road',
    '干諾道中': 'Connaught Road Central',
    '中環灣仔繞道': 'Central-Wan Chai Bypass',
    '窩打老道': 'Waterloo Road',
    '漆咸道北': 'Chatham Road North',
    '太子道東': 'Prince Edward Road East',
    '新清水灣道': 'New Clear Water Bay Road',
    '清水灣道': 'Clear Water Bay Road',
    '西貢公路': 'Sai Kung Highway',
    '西沙路': 'Sai Sha Road',
    '馬鞍山路': 'Ma On Shan Road',
    '大老山公路': 'Tate\'s Cairn Highway',
    '大埔公路': 'Tai Po Road',
    '青山公路': 'Castle Peak Road',
    '荔寶路': 'Lai Po Road',
    '連翔道': 'Lin Cheung Road',
    '荔枝角道': 'Lai Chi Kok Road',
    '麗翔道': 'Lai Cheung Road',
    '佛光街': 'Fat Kwong Street',
    '梭椏道': 'Soares Avenue',
    '亞皆老街': 'Argyle Street',
    '康莊道': 'Wuhong Street',
    '中九龍繞道': 'Central Kowloon Bypass',
    '青衣南橋': 'Tsing Yi South Bridge',
    '青衣北橋': 'Tsing Yi North Bridge',
    '東九龍走廊': 'East Kowloon Corridor',
    '西九龍走廊': 'West Kowloon Corridor',
    '紅棉路': 'Cotton Tree Drive',
    '干諾道西天橋': 'Connaught Road West Flyover',
    '林錦公路': 'Lam Kam Road',
    '大河道': 'Tai Ho Road',
    '象鼻山道': 'Cheung Pei Shan Road',
    '青松觀路': 'Tsing Chung Koon Road',
    '屯門公路': 'Tuen Mun Road',
    '新屯門公路': 'New Tuen Mun Road',
    '元朗公路': 'Yuen Long Highway',
    '朗屏路': 'Long Ping Road',
    '吐露港公路': 'Tolo Highway',
    '粉嶺公路': 'Fanling Highway',
    '新田公路': 'San Tin Highway',
    '港深西部公路': 'Hong Kong-Shenzhen Western Corridor',
    '深旺道': 'Sham Mong Road',
    '葵涌道': 'Kwai Chung Road',
    '呈祥道': 'Ching Cheung Road',
    '龍富路': 'Lung Fu Road',
    '皇珠路': 'Wong Chu Road',
    '海旁道': 'Praya Road',
    '沙燕橋': 'Sha Yan Bridge',
    '大涌橋路': 'Tai Chung Kiu Road',
    '獅子山': 'Lion Rock',
    '香港瞳': '',
    # exam vocabulary
    '道路使用者守則': "Road Users' Code",
    '的士及網約車': 'taxi and ride-hailing vehicle',
    '網約車': 'ride-hailing vehicle',
    '的士': 'taxi',
    '車隊牌照': 'taxi fleet licence',
    '客運營業證': 'Passenger Service Licence',
    '出租汽車許可證': 'Hire Car Permit',
    '登記車主': 'registered owner',
    '司機證': 'taxi driver identity plate',
    '載客服務': 'passenger service',
    '出租或取酬': 'for hire or reward',
    '收費錶': 'taximeter',
    '咪錶': 'taximeter',
    '八達通': 'Octopus card',
    '易通行': 'HKeToll',
    '低排放區': 'low emission zone',
    '禁區': 'restricted zone',
    '白色實線': 'white solid line',
    '雙白線': 'double white lines',
    '停止線': 'stop line',
    '讓路線': 'give way line',
    '斑馬線': 'zebra crossing',
    '過路處': 'crossing',
    '行人天橋': 'footbridge',
    '行人隧道': 'subway',
    '安全島': 'traffic island',
    '迴旋處': 'roundabout',
    '主幹路': 'major road',
    '幹路': 'main road',
    '單程路': 'one-way road',
    '雙程路': 'two-way road',
    '快線': 'offside lane',
    '慢線': 'nearside lane',
    '超車': 'overtake',
    '扒頭': 'overtake',
    '車速限制': 'speed limit',
    '最高車速': 'maximum speed',
    '思考距離': 'thinking distance',
    '剎車距離': 'braking distance',
    '停車距離': 'stopping distance',
    '盲點': 'blind spot',
    '酒後駕駛': 'drink driving',
    '藥後駕駛': 'drug driving',
    '呼氣測試': 'breath test',
    '酒精濃度': 'alcohol concentration',
    '危險駕駛': 'dangerous driving',
    '不小心駕駛': 'careless driving',
    '交通燈': 'traffic lights',
    '紅燈': 'red light',
    '綠燈': 'green light',
    '黃燈': 'amber light',
    '閃亮': 'flashing',
    '常亮': 'steady',
    '交通標誌': 'traffic sign',
    '道路標記': 'road marking',
    '警告標誌': 'warning sign',
    '禁制標誌': 'restrictive sign',
    '強制標誌': 'mandatory sign',
    '資訊標誌': 'information sign',
    '方向標誌': 'direction sign',
    '不准停車': 'no stopping',
    '不准上落乘客': 'no pick-up or drop-off',
    '泊車': 'parking',
    '停車': 'stop',
    '讓路': 'give way',
    '響號': 'horn',
    '倒後鏡': 'rear-view mirror',
    '倒車': 'reversing',
    '掉頭': 'U-turn',
    '轉線': 'change lane',
    '切線': 'cut in',
    '左轉': 'turn left',
    '右轉': 'turn right',
    '靠左': 'keep left',
    '靠右': 'keep right',
    '車頭燈': 'headlights',
    '車尾燈': 'tail lights',
    '死火燈': 'hazard warning lights',
    '霧燈': 'fog lamps',
    '安全帶': 'seat belt',
    '兒童座椅': 'child restraint',
    '氣袋': 'airbag',
    '斑馬': 'zebra',
    '行人路': 'footway',
    '車路': 'carriageway',
    '行人': 'pedestrian',
    '騎單車者': 'cyclist',
    '電單車': 'motor cycle',
    '機動三輪車': 'motor tricycle',
    '私家車': 'private car',
    '貨車': 'goods vehicle',
    '巴士': 'bus',
    '公共小型巴士': 'public light bus',
    '專線小巴': 'green minibus',
    '學習駕駛人': 'learner driver',
    '學習駕駛執照': 'learner\'s driving licence',
    '暫准駕駛執照': 'probationary driving licence',
    '正式駕駛執照': 'full driving licence',
    '駕駛執照': 'driving licence',
    '駕駛執照': 'driving licence',
    '身份證': 'identity card',
    '車輛登記文件': 'vehicle registration document',
    '第三者保險': 'third party insurance',
    '交通意外': 'traffic accident',
    '意外': 'accident',
    '緊急車輛': 'emergency vehicle',
    '救護車': 'ambulance',
    '消防車': 'fire appliance',
    '警車': 'police car',
    '小學校區': 'school zone',
    '學校': 'school',
    '醫院': 'hospital',
    '隧道收費': 'tunnel fee',
    '收費廣場': 'toll plaza',
    '自動繳費': 'autotoll',
    '行車線': 'lane',
    '車道': 'lane',
    '路口': 'junction',
    '十字路口': 'crossroads',
    'T字路口': 'T-junction',
    '交通交匯處': 'interchange',
    '天橋': 'flyover',
    '行車天橋': 'flyover',
    '斜路': 'slope',
    '陡斜斜路': 'steep hill',
    '彎路': 'bend',
    '急彎': 'sharp bend',
    '窄路': 'narrow road',
    '濕滑': 'slippery',
    '薄霧': 'mist',
    '霧': 'fog',
    '大雨': 'heavy rain',
    '夜間': 'at night',
    '晚間': 'at night',
    '引擎': 'engine',
    '煞車系統': 'braking system',
    '制動系統': 'braking system',
    '軚盤': 'steering wheel',
    '輪胎': 'tyre',
    '花紋深度': 'tread depth',
    '車輛檢驗': 'vehicle examination',
    '運輸署': 'Transport Department',
    '運輸署署長': 'Commissioner for Transport',
    '警務處': 'Police Force',
    '環境保護署': 'Environmental Protection Department',
    '牌照': 'licence',
    '許可證': 'permit',
    '申請': 'apply',
    '費用': 'fee',
    '罰款': 'fine',
    '扣分': 'points',
    '違例駕駛記分': 'driving-offence points',
    '定額罰款': 'fixed penalty',
    '法庭': 'court',
    '檢控': 'prosecution',
    '在正常交通情況下': 'under normal traffic conditions',
    '最直接可行': 'most direct viable',
    '路線': 'route',
    '位置': 'location',
    '地方': 'place',
}


def glossary_sub(text):
    """Replace zh terms with %%N%% placeholders; returns (protected_text, mapping)."""
    spans = []
    for term in sorted(TERMS, key=len, reverse=True):
        for m in re.finditer(re.escape(term), text):
            # skip overlaps
            if any(not (m.end() <= s or m.start() >= e) for s, e, _ in spans):
                continue
            spans.append((m.start(), m.end(), term))
    spans.sort()
    out, last, mapping = [], 0, {}
    for i, (s, e, term) in enumerate(spans):
        out.append(text[last:s])
        out.append(f'%%{i}%%')
        mapping[f'%%{i}%%'] = term
        last = e
    out.append(text[last:])
    return ''.join(out), mapping
