"""Manual EN overrides for suspect options."""
OPT_OVERRIDES = {
    '不可使用巴士線': 'must not use the bus lane',
    '不可停車，除非要讓行人過馬路，或正等候轉左或轉右': 'no stopping except to let pedestrians cross, or while waiting to turn left or right',
    '不可泊車，但在劃定界線的泊車處除外': 'no parking except in marked parking spaces',
    '不得在快速公路任何一處停車或泊車': 'must not stop or park anywhere on an expressway',
    '不設，因為一經駛入快速公路，在正常交通情況下便不准停車': 'none, because once on an expressway stopping is prohibited under normal traffic conditions',
    '仍可申請網約車車輛駕駛許可證': 'may still apply for a ride-hailing vehicle driving permit',
    '任選行車線': 'any lane',
    '使用認可兒童束縛設備穩妥繫於座位上': 'secured to the seat with an approved child restraint',
    '供網約車候客': 'for ride-hailing vehicles to wait for passengers',
    '依循交通標誌或路面上的行車線箭嘴指示，預先選定及駛入適當的行車線': 'follow the traffic signs or lane arrows on the road and choose and move into the proper lane in advance',
    '俱屬無效': 'both are invalid',
    '分隔行車線與巴士線': 'separating a traffic lane from a bus lane',
    '切勿使用在該燈號以後的行車線': 'do not use the lanes beyond that signal',
    '前進至右轉袋口位等候，直至迎面車輛之間有安全空隙才可右轉': 'move forward into the right-turn pocket and wait until there is a safe gap in oncoming traffic before turning right',
    '劃定界線的泊車處': 'marked parking space',
    '只可在日間泊車': 'parking in daytime only',
    '只可在日間超車': 'overtaking in daytime only',
    '只可在日間轉線': 'lane changing in daytime only',
    '只可從右方超車，切勿駛入左線超車，也不可利用路肩超車': 'overtake on the right only; never overtake by moving into a left lane or by using the hard shoulder',
    '司機持有的士駕駛執照': 'the taxi driving licence held by the driver',
    '向的士車主租賃的士駕駛的司機': 'a driver who rents a taxi from the taxi owner to drive it',
    '向運輸署申請': 'apply to the Transport Department',
    '在安全情況下，可駛過路口或行人過路處': 'if safe, you may drive on through the junction or pedestrian crossing',
    '在所示時間內不准停車': 'no stopping during the times shown',
    '在指定其類型之的士站，或乘客提出要求或有意乘車的乘客示意時': 'at a taxi stand of its type, or when a hirer requests or an intending passenger signals',
    '在有需要而且情況安全時才可切線，盡量保持在行車線中間行駛': 'change lanes only when necessary and safe, and keep well within the middle of the lane',
    '在計程錶車費外收取預先協定的預約費用，或行程開始前協定的整筆車費': 'charge a pre-agreed booking fee on top of the metered fare, or a lump-sum fare agreed before the journey begins',
    '在路障截查行動中被隨機截停的駕駛人、涉及交通意外或觸犯交通違例事項或涉嫌酒後駕駛的駕駛人': 'drivers randomly stopped at roadblocks, drivers involved in traffic accidents or committing traffic offences, and drivers suspected of drink driving',
    '實際車速所需的停車距離，更容易超出車速限制': 'the stopping distance required at the actual speed is more likely to exceed the speed limit',
    '市區、郊區及機場的士牌照': 'urban, New Territory and Lantau taxi licences',
    '必須使用兒童束縛設備': 'must use a child restraint',
    '持有的士牌照的個人': 'an individual holding a taxi licence',
    '有效之的士駕駛執照及的士司機證': 'a valid taxi driving licence and a taxi driver identity plate',
    '有效網約車車輛許可證': 'a valid ride-hailing vehicle permit',
    '減低車速甚或停車，把路口當作非交通燈控制路口處理，格外小心慢慢駛過': 'slow down or even stop, treat the junction as an uncontrolled junction, and pass it slowly with extra care',
    '由運輸署發出的網約車車輛證明書': 'the ride-hailing vehicle certificate issued by the Transport Department',
    '的士可供夜間出租時間': 'the hours during which the taxi is available for hire at night',
    '的士商會': 'taxi trade associations',
    '的士車隊': 'taxi fleet',
    '立即倒車': 'reverse immediately',
    '立即停車': 'stop immediately',
    '立即停車，並切勿駛越這標誌，這標誌會在薄霧天氣消除後才被移除': 'stop immediately and do not pass this sign; it will be removed only after the mist clears',
    '立即右轉': 'turn right immediately',
    '紅色、綠色及黃色的士牌照': 'red, green and blue taxi licences',
    '絕對不可開動引擎，或讓引擎運轉': 'never start the engine or leave it running',
    '進行涉及倒車的操作時（例如用「三手軚」掉頭）': 'when carrying out a manoeuvre involving reversing (such as a three-point turn)',
    '領有有效網約車服務牌照的網約車平台': 'a ride-hailing platform holding a valid ride-hailing service licence',
    '十項': 'ten offences',
}
